### ISSUE TITLE
Crash on exit

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Cockatrice#2413]
<b>OS:</b>
Arch Linux (i3wm)

<b>Cockatrice version:</b>
3498b16e

___
<br>

My best guess is that this has something to do with the fact that I don't have a system tray on my copy of Arch.

```
┌[homeにarch]-(~)
└> gdb cockatrice cockatrice.core                                                                                
GNU gdb (GDB) 7.12.1
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from cockatrice...(no debugging symbols found)...done.
[New LWP 9582]
[New LWP 9586]
[New LWP 9585]
[New LWP 9584]
[New LWP 9583]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
Core was generated by `/usr/bin/cockatrice'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f6431188455 in QSystemTrayIcon::setVisible(bool) () from /usr/lib/libQt5Widgets.so.5
[Current thread is 1 (Thread 0x7f6432432280 (LWP 9582))]
(gdb) bt
#0  0x00007f6431188455 in QSystemTrayIcon::setVisible(bool) () from /usr/lib/libQt5Widgets.so.5
#1  0x00000000005a6b43 in MainWindow::~MainWindow() ()
#2  0x0000000000557280 in main ()
(gdb) 
```

**Comment by Daenyth** [comment]
This seems like it should be an easy fix

**Comment by skwerlman** [comment]
I just realized that the version in AUR is _very_ out of date, so I tested again with the current version built from source, and got the same result:
```
(gdb) run
Starting program: /usr/local/bin/cockatrice 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffe98f7700 (LWP 21691)]
[New Thread 0x7fffe3984700 (LWP 21692)]
[New Thread 0x7fffe3183700 (LWP 21693)]
[New Thread 0x7fffe2057700 (LWP 21694)]
[New Thread 0x7fffe0f75700 (LWP 21918)]
[New Thread 0x7fffd222d700 (LWP 21919)]
[New Thread 0x7fffd1a2c700 (LWP 21920)]
[Thread 0x7fffd1a2c700 (LWP 21920) exited]
[Thread 0x7fffd222d700 (LWP 21919) exited]

Thread 1 "cockatrice" received signal SIGSEGV, Segmentation fault.
0x00007ffff6829455 in QSystemTrayIcon::setVisible(bool) () from /usr/lib/libQt5Widgets.so.5
(gdb) bt
#0  0x00007ffff6829455 in QSystemTrayIcon::setVisible(bool) () from /usr/lib/libQt5Widgets.so.5
#1  0x00000000005b8043 in MainWindow::~MainWindow() ()
#2  0x0000000000561767 in main ()
```

**Comment by ZeldaZach** [comment]
@skwerlman Can you try out #2415 and lmk if it works properly?

**Comment by skwerlman** [comment]
Sure, I'll try it out and edit with results.
