### ISSUE TITLE
Crash when removing card from deck

### ISSUE THREAD

**Issue by escobera** [Cockatrice/Cockatrice#3133]
<b>OS: Linux Mint 18.3</b>

<b>Cockatrice version: 2a9d76f (2018-03-07)</b>
__________

Title says it all, happens almost every time when trying to remove cards. Happens more often on sideboard.

GDB bt
```
Thread 1 "cockatrice" received signal SIGSEGV, Segmentation fault.
0x00000000006ea270 in AbstractDecklistNode::getParent (this=0x1)
    at /home/rafa/projects/Cockatrice/cockatrice/../common/decklist.h:74
74	        return parent;
(gdb) bt
#0  0x00000000006ea270 in AbstractDecklistNode::getParent (this=0x1)
    at /home/rafa/projects/Cockatrice/cockatrice/../common/decklist.h:74
#1  0x00000000006e8fb2 in DeckListModel::nodeToIndex (this=0x159a480, node=0x1)
    at /home/rafa/projects/Cockatrice/cockatrice/src/decklistmodel.cpp:357
#2  0x00000000006e8000 in DeckListModel::parent (this=0x159a480, ind=...)
    at /home/rafa/projects/Cockatrice/cockatrice/src/decklistmodel.cpp:187
#3  0x00007ffff76c8f7b in QTreeView::isIndexHidden(QModelIndex const&) const ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#4  0x00007ffff76caea7 in QTreeView::visualRect(QModelIndex const&) const ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#5  0x00007ffff76715da in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00007fffec008273 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#7  0x00007fffec00fade in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#8  0x00007fffec00ff49 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#9  0x00007fffec0153ac in ?? () from /usr/lib/x86_64-linux-gnu/libQt5XcbQpa.so.5
#10 0x00007fffe9a13abe in ?? () from /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#11 0x00007fffe9a1526e in ?? () from /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5
#12 0x00007ffff6b69c01 in QObject::event(QEvent*) () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#13 0x00007ffff742d05c in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#14 0x00007ffff7432516 in QApplication::notify(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#15 0x00007ffff6b3a38b in QCoreApplication::notifyInternal(QObject*, QEvent*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007ffff6b3c786 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00007ffff6b903c3 in ?? () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#18 0x00007ffff4e87197 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#19 0x00007ffff4e873f0 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#20 0x00007ffff4e8749c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#21 0x00007ffff6b907cf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#22 0x00007ffff6b37b4a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#23 0x00007ffff6b3fbec in QCoreApplication::exec() () from /usr/lib/x86_64-linux-gnu/libQt5Core.so.5
#24 0x0000000000687003 in main (argc=1, argv=0x7fffffffde18)
    at /home/rafa/projects/Cockatrice/cockatrice/src/main.cpp:147
```

**Comment by skwerlman** [comment]
@Daenyth OS tag should be linux not macOS

**Comment by Daenyth** [comment]
Derp

**Comment by escobera** [comment]
I'm still having this problem on master. 

@Daenyth Is there any way I can help debug/fix this issue?

**Comment by ZeldaZach** [comment]
Hey dude. From looking at it, maybe there’s a bad value in the decklist file in the common folder. I’m on mobile rn so I can’t look, but that might be a good starting place. Join us on gitter any time for further help :)

**Comment by escobera** [comment]
I've upgraded my QT5 version from 5.5.1 to 5.11.1 and compiled cockatrice again. The bug seems to be gone now. Maybe it's a bug in this version of QT?

**Comment by tooomm** [comment]
@escobera Maybe... Could you try some other versions of Qt to better understand where it's fixed? Like 5.6 LTS and 5.9 LTS

**Comment by escobera** [comment]
@tooomm ok

**5.6.3**  Can't reproduce.
**5.9.6**  Can't reproduce.
**5.11.1**  Can't reproduce.

So it seems the problem was on version 5.5.1 that I was using before

**Comment by ZeldaZach** [comment]
If this is still an issue on the latest build, please let us know
