### ISSUE TITLE
Client crash when closing game

### ISSUE THREAD

**Issue by skwerlman** [Cockatrice/Cockatrice#4167]
<b>System Information:</b>
Cockatrice 2.7.6-custom(f11f072) (2020-11-08)
Archlinux 5.9.8-zen1-1-zen
_______________________________________________________________________________________

The client crashed when i pressed the X to close the game tab. I was spectating the game after conceding. Maybe related to #3212, but the trace looks pretty different to me.

<details><summary>Crash info</summary>

GDB `bt`:
```
#0  0x00007f49bc64d615 in raise () from /usr/lib/libc.so.6
#1  0x00007f49bc636862 in abort () from /usr/lib/libc.so.6
#2  0x00007f49bc9d186a in __gnu_cxx::__verbose_terminate_handler () at /build/gcc/src/gcc/libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007f49bc9ddd9a in __cxxabiv1::__terminate (handler=<optimized out>) at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:48
#4  0x00007f49bc9dcd4a in __cxa_call_terminate (ue_header=ue_header@entry=0x5624566ce2e0) at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_call.cc:54
#5  0x00007f49bc9dd722 in __cxxabiv1::__gxx_personality_v0 (version=<optimized out>, actions=6, exception_class=5138137972254386944, ue_header=0x5624566ce2e0, context=<optimized out>) at /build/gcc/src/gcc/libstdc++-v3/libsupc++/eh_personality.cc:685
#6  0x00007f49bc7eb6b0 in _Unwind_RaiseException_Phase2 (exc=0x5624566ce2e0, context=0x7ffff658e380, frames_p=0x7ffff658e288) at /build/gcc/src/gcc/libgcc/unwind.inc:64
#7  0x00007f49bc7ec0ee in _Unwind_Resume (exc=0x5624566ce2e0) at /build/gcc/src/gcc/libgcc/unwind.inc:241
#8  0x000056244715678e in ?? ()
#9  0x0000562447205d96 in Player::~Player() ()
#10 0x000056244720612a in Player::~Player() ()
#11 0x000056244727ce45 in TabGame::~TabGame() ()
#12 0x000056244727d23a in TabGame::~TabGame() ()
#13 0x00007f49bcdf85a0 in QObject::event(QEvent*) () from /usr/lib/libQt5Core.so.5
#14 0x00007f49bdd80752 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#15 0x00007f49bcdcbcda in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#16 0x00007f49bcdce7d3 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/libQt5Core.so.5
#17 0x00007f49bce25304 in ?? () from /usr/lib/libQt5Core.so.5
#18 0x00007f49bb840914 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#19 0x00007f49bb8947d1 in ?? () from /usr/lib/libglib-2.0.so.0
#20 0x00007f49bb83f121 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#21 0x00007f49bce24941 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#22 0x00007f49bcdca65c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#23 0x00007f49bcdd2af4 in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#24 0x0000562447181639 in main ()
```

coredumpctl trace:
```
                Stack trace of thread 86097:
                #0  0x00007f49bc64d615 raise (libc.so.6 + 0x3d615)
                #1  0x00007f49bc636862 abort (libc.so.6 + 0x26862)
                #2  0x00007f49bc9d186a _ZN9__gnu_cxx27__verbose_terminate_handlerEv (libstdc++.so.6 + 0x9686a)
                #3  0x00007f49bc9ddd9a _ZN10__cxxabiv111__terminateEPFvvE (libstdc++.so.6 + 0xa2d9a)
                #4  0x00007f49bc9dcd4a __cxa_call_terminate (libstdc++.so.6 + 0xa1d4a)
                #5  0x00007f49bc9dd722 __gxx_personality_v0 (libstdc++.so.6 + 0xa2722)
                #6  0x00007f49bc7eb6b0 _Unwind_RaiseException_Phase2 (libgcc_s.so.1 + 0x106b0)
                #7  0x00007f49bc7ec0ee _Unwind_Resume (libgcc_s.so.1 + 0x110ee)
                #8  0x000056244715678e n/a (cockatrice + 0x1a878e)
                #9  0x0000562447205d96 _ZN6PlayerD1Ev (cockatrice + 0x257d96)
                #10 0x000056244720612a _ZN6PlayerD0Ev (cockatrice + 0x25812a)
                #11 0x000056244727ce45 _ZN7TabGameD1Ev (cockatrice + 0x2cee45)
                #12 0x000056244727d23a _ZN7TabGameD0Ev (cockatrice + 0x2cf23a)
                #13 0x00007f49bcdf85a0 _ZN7QObject5eventEP6QEvent (libQt5Core.so.5 + 0x2e05a0)
                #14 0x00007f49bdd80752 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5 + 0x15a752)
                #15 0x00007f49bcdcbcda _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5 + 0x2b3cda)
                #16 0x00007f49bcdce7d3 _ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData (libQt5Core.so.5 + 0x2b67d3)
                #17 0x00007f49bce25304 n/a (libQt5Core.so.5 + 0x30d304)
                #18 0x00007f49bb840914 g_main_context_dispatch (libglib-2.0.so.0 + 0x52914)
                #19 0x00007f49bb8947d1 n/a (libglib-2.0.so.0 + 0xa67d1)
                #20 0x00007f49bb83f121 g_main_context_iteration (libglib-2.0.so.0 + 0x51121)
                #21 0x00007f49bce24941 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x30c941)
                #22 0x00007f49bcdca65c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2b265c)
                #23 0x00007f49bcdd2af4 _ZN16QCoreApplication4execEv (libQt5Core.so.5 + 0x2baaf4)
                #24 0x0000562447181639 main (cockatrice + 0x1d3639)
                #25 0x00007f49bc638152 __libc_start_main (libc.so.6 + 0x28152)
                #26 0x000056244718821e _start (cockatrice + 0x1da21e)
                
                Stack trace of thread 86101:
                #0  0x00007f49bc70546f __poll (libc.so.6 + 0xf546f)
                #1  0x00007f49bb89475f n/a (libglib-2.0.so.0 + 0xa675f)
                #2  0x00007f49bb83f121 g_main_context_iteration (libglib-2.0.so.0 + 0x51121)
                #3  0x00007f49bce24941 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x30c941)
                #4  0x00007f49bcdca65c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2b265c)
                #5  0x00007f49bcbe4ca2 _ZN7QThread4execEv (libQt5Core.so.5 + 0xccca2)
                #6  0x00007f49bcbe5e8f n/a (libQt5Core.so.5 + 0xcde8f)
                #7  0x00007f49bd8c33e9 start_thread (libpthread.so.0 + 0x93e9)
                #8  0x00007f49bc710293 __clone (libc.so.6 + 0x100293)
                
                Stack trace of thread 86098:
                #0  0x00007f49bc70546f __poll (libc.so.6 + 0xf546f)
                #1  0x00007f49b964563b n/a (libxcb.so.1 + 0xc63b)
                #2  0x00007f49b964737b xcb_wait_for_event (libxcb.so.1 + 0xe37b)
                #3  0x00007f49b8f69f61 n/a (libQt5XcbQpa.so.5 + 0x5df61)
                #4  0x00007f49bcbe5e8f n/a (libQt5Core.so.5 + 0xcde8f)
                #5  0x00007f49bd8c33e9 start_thread (libpthread.so.0 + 0x93e9)
                #6  0x00007f49bc710293 __clone (libc.so.6 + 0x100293)
                
                Stack trace of thread 86302:
                #0  0x00007f49bc707c96 pselect (libc.so.6 + 0xf7c96)
                #1  0x00007f49b2806524 n/a (libusbmuxd-2.0.so.6 + 0x2524)
                #2  0x00007f49b28078a9 n/a (libusbmuxd-2.0.so.6 + 0x38a9)
                #3  0x00007f49bd8c33e9 start_thread (libpthread.so.0 + 0x93e9)
                #4  0x00007f49bc710293 __clone (libc.so.6 + 0x100293)
                
                Stack trace of thread 86362:
                #0  0x00007f49bc70546f __poll (libc.so.6 + 0xf546f)
                #1  0x00007f49bb89475f n/a (libglib-2.0.so.0 + 0xa675f)
                #2  0x00007f49bb83f121 g_main_context_iteration (libglib-2.0.so.0 + 0x51121)
                #3  0x00007f49bce24941 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x30c941)
                #4  0x00007f49bcdca65c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2b265c)
                #5  0x00007f49bcbe4ca2 _ZN7QThread4execEv (libQt5Core.so.5 + 0xccca2)
                #6  0x00007f49bcbe5e8f n/a (libQt5Core.so.5 + 0xcde8f)
                #7  0x00007f49bd8c33e9 start_thread (libpthread.so.0 + 0x93e9)
                #8  0x00007f49bc710293 __clone (libc.so.6 + 0x100293)
                
                Stack trace of thread 86100:
                #0  0x00007f49bc70546f __poll (libc.so.6 + 0xf546f)
                #1  0x00007f49bb89475f n/a (libglib-2.0.so.0 + 0xa675f)
                #2  0x00007f49bb83f121 g_main_context_iteration (libglib-2.0.so.0 + 0x51121)
                #3  0x00007f49bce24941 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x30c941)
                #4  0x00007f49bcdca65c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2b265c)
                #5  0x00007f49bcbe4ca2 _ZN7QThread4execEv (libQt5Core.so.5 + 0xccca2)
                #6  0x00007f49bcbe5e8f n/a (libQt5Core.so.5 + 0xcde8f)
                #7  0x00007f49bd8c33e9 start_thread (libpthread.so.0 + 0x93e9)
                #8  0x00007f49bc710293 __clone (libc.so.6 + 0x100293)
                
                Stack trace of thread 145480:
                #0  0x00007f49bd8c99c8 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf9c8)
                #1  0x00007f49bcbec058 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5 + 0xd4058)
                #2  0x00007f49bcbe9fc4 n/a (libQt5Core.so.5 + 0xd1fc4)
                #3  0x00007f49bcbe5e8f n/a (libQt5Core.so.5 + 0xcde8f)
                #4  0x00007f49bd8c33e9 start_thread (libpthread.so.0 + 0x93e9)
                #5  0x00007f49bc710293 __clone (libc.so.6 + 0x100293)
                
                Stack trace of thread 145533:
                #0  0x00007f49bd8c99c8 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf9c8)
                #1  0x00007f49bcbec058 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5 + 0xd4058)
                #2  0x00007f49bcbe9fc4 n/a (libQt5Core.so.5 + 0xd1fc4)
                #3  0x00007f49bcbe5e8f n/a (libQt5Core.so.5 + 0xcde8f)
                #4  0x00007f49bd8c33e9 start_thread (libpthread.so.0 + 0x93e9)
                #5  0x00007f49bc710293 __clone (libc.so.6 + 0x100293)
                
                Stack trace of thread 145490:
                #0  0x00007f49bd8c99c8 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf9c8)
                #1  0x00007f49bcbec058 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5 + 0xd4058)
                #2  0x00007f49bcbe9fc4 n/a (libQt5Core.so.5 + 0xd1fc4)
                #3  0x00007f49bcbe5e8f n/a (libQt5Core.so.5 + 0xcde8f)
                #4  0x00007f49bd8c33e9 start_thread (libpthread.so.0 + 0x93e9)
                #5  0x00007f49bc710293 __clone (libc.so.6 + 0x100293)
                
                Stack trace of thread 145487:
                #0  0x00007f49bd8c99c8 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf9c8)
                #1  0x00007f49bcbec058 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5 + 0xd4058)
                #2  0x00007f49bcbe9fc4 n/a (libQt5Core.so.5 + 0xd1fc4)
                #3  0x00007f49bcbe5e8f n/a (libQt5Core.so.5 + 0xcde8f)
                #4  0x00007f49bd8c33e9 start_thread (libpthread.so.0 + 0x93e9)
                #5  0x00007f49bc710293 __clone (libc.so.6 + 0x100293)
                
                Stack trace of thread 145530:
                #0  0x00007f49bd8c99c8 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf9c8)
                #1  0x00007f49bcbec058 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5 + 0xd4058)
                #2  0x00007f49bcbe9fc4 n/a (libQt5Core.so.5 + 0xd1fc4)
                #3  0x00007f49bcbe5e8f n/a (libQt5Core.so.5 + 0xcde8f)
                #4  0x00007f49bd8c33e9 start_thread (libpthread.so.0 + 0x93e9)
                #5  0x00007f49bc710293 __clone (libc.so.6 + 0x100293)
                
                Stack trace of thread 145488:
                #0  0x00007f49bd8c99c8 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf9c8)
                #1  0x00007f49bcbec058 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5 + 0xd4058)
                #2  0x00007f49bcbe9fc4 n/a (libQt5Core.so.5 + 0xd1fc4)
                #3  0x00007f49bcbe5e8f n/a (libQt5Core.so.5 + 0xcde8f)
                #4  0x00007f49bd8c33e9 start_thread (libpthread.so.0 + 0x93e9)
                #5  0x00007f49bc710293 __clone (libc.so.6 + 0x100293)
                
                Stack trace of thread 86112:
                #0  0x00007f49bc70546f __poll (libc.so.6 + 0xf546f)
                #1  0x00007f49bb89475f n/a (libglib-2.0.so.0 + 0xa675f)
                #2  0x00007f49bb83f121 g_main_context_iteration (libglib-2.0.so.0 + 0x51121)
                #3  0x00007f49bce2495c _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x30c95c)
                #4  0x00007f49bcdca65c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2b265c)
                #5  0x00007f49bcbe4ca2 _ZN7QThread4execEv (libQt5Core.so.5 + 0xccca2)
                #6  0x00007f49bcbe5e8f n/a (libQt5Core.so.5 + 0xcde8f)
                #7  0x00007f49bd8c33e9 start_thread (libpthread.so.0 + 0x93e9)
                #8  0x00007f49bc710293 __clone (libc.so.6 + 0x100293)
                
                Stack trace of thread 145489:
                #0  0x00007f49bd8c99c8 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf9c8)
                #1  0x00007f49bcbec058 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5 + 0xd4058)
                #2  0x00007f49bcbe9fc4 n/a (libQt5Core.so.5 + 0xd1fc4)
                #3  0x00007f49bcbe5e8f n/a (libQt5Core.so.5 + 0xcde8f)
                #4  0x00007f49bd8c33e9 start_thread (libpthread.so.0 + 0x93e9)
                #5  0x00007f49bc710293 __clone (libc.so.6 + 0x100293)
                
                Stack trace of thread 86131:
                #0  0x00007f49bd8c96a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                #1  0x00007f49bcbec0d4 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5 + 0xd40d4)
                #2  0x00007f49bdfad503 n/a (libQt5Widgets.so.5 + 0x387503)
                #3  0x00007f49bcbe5e8f n/a (libQt5Core.so.5 + 0xcde8f)
                #4  0x00007f49bd8c33e9 start_thread (libpthread.so.0 + 0x93e9)
                #5  0x00007f49bc710293 __clone (libc.so.6 + 0x100293)
                
                Stack trace of thread 145532:
                #0  0x00007f49bd8c99c8 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf9c8)
                #1  0x00007f49bcbec058 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5 + 0xd4058)
                #2  0x00007f49bcbe9fc4 n/a (libQt5Core.so.5 + 0xd1fc4)
                #3  0x00007f49bcbe5e8f n/a (libQt5Core.so.5 + 0xcde8f)
                #4  0x00007f49bd8c33e9 start_thread (libpthread.so.0 + 0x93e9)
                #5  0x00007f49bc710293 __clone (libc.so.6 + 0x100293)
                
                Stack trace of thread 86099:
                #0  0x00007f49bc70546f __poll (libc.so.6 + 0xf546f)
                #1  0x00007f49bb89475f n/a (libglib-2.0.so.0 + 0xa675f)
                #2  0x00007f49bb83f121 g_main_context_iteration (libglib-2.0.so.0 + 0x51121)
                #3  0x00007f49bce24941 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x30c941)
                #4  0x00007f49bcdca65c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2b265c)
                #5  0x00007f49bcbe4ca2 _ZN7QThread4execEv (libQt5Core.so.5 + 0xccca2)
                #6  0x00007f49b8e9d098 n/a (libQt5DBus.so.5 + 0x17098)
                #7  0x00007f49bcbe5e8f n/a (libQt5Core.so.5 + 0xcde8f)
                #8  0x00007f49bd8c33e9 start_thread (libpthread.so.0 + 0x93e9)
                #9  0x00007f49bc710293 __clone (libc.so.6 + 0x100293)
                
                Stack trace of thread 145486:
                #0  0x00007f49bd8c99c8 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf9c8)
                #1  0x00007f49bcbec058 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5 + 0xd4058)
                #2  0x00007f49bcbe9fc4 n/a (libQt5Core.so.5 + 0xd1fc4)
                #3  0x00007f49bcbe5e8f n/a (libQt5Core.so.5 + 0xcde8f)
                #4  0x00007f49bd8c33e9 start_thread (libpthread.so.0 + 0x93e9)
                #5  0x00007f49bc710293 __clone (libc.so.6 + 0x100293)
                
                Stack trace of thread 145531:
                #0  0x00007f49bd8c99c8 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf9c8)
                #1  0x00007f49bcbec058 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5 + 0xd4058)
                #2  0x00007f49bcbe9fc4 n/a (libQt5Core.so.5 + 0xd1fc4)
                #3  0x00007f49bcbe5e8f n/a (libQt5Core.so.5 + 0xcde8f)
                #4  0x00007f49bd8c33e9 start_thread (libpthread.so.0 + 0x93e9)
                #5  0x00007f49bc710293 __clone (libc.so.6 + 0x100293)
                
                Stack trace of thread 86363:
                #0  0x00007f49bc70546f __poll (libc.so.6 + 0xf546f)
                #1  0x00007f49bb89475f n/a (libglib-2.0.so.0 + 0xa675f)
                #2  0x00007f49bb83f121 g_main_context_iteration (libglib-2.0.so.0 + 0x51121)
                #3  0x00007f49bce24941 _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x30c941)
                #4  0x00007f49bcdca65c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2b265c)
                #5  0x00007f49bcbe4ca2 _ZN7QThread4execEv (libQt5Core.so.5 + 0xccca2)
                #6  0x00007f49bcbe5e8f n/a (libQt5Core.so.5 + 0xcde8f)
                #7  0x00007f49bd8c33e9 start_thread (libpthread.so.0 + 0x93e9)
                #8  0x00007f49bc710293 __clone (libc.so.6 + 0x100293)
                
                Stack trace of thread 86140:
                #0  0x00007f49bc70546f __poll (libc.so.6 + 0xf546f)
                #1  0x00007f49bb89475f n/a (libglib-2.0.so.0 + 0xa675f)
                #2  0x00007f49bb83f121 g_main_context_iteration (libglib-2.0.so.0 + 0x51121)
                #3  0x00007f49bce2495c _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5 + 0x30c95c)
                #4  0x00007f49bcdca65c _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5 + 0x2b265c)
                #5  0x00007f49bcbe4ca2 _ZN7QThread4execEv (libQt5Core.so.5 + 0xccca2)
                #6  0x00007f49bcbe5e8f n/a (libQt5Core.so.5 + 0xcde8f)
                #7  0x00007f49bd8c33e9 start_thread (libpthread.so.0 + 0x93e9)
                #8  0x00007f49bc710293 __clone (libc.so.6 + 0x100293)
                
                Stack trace of thread 86132:
                #0  0x00007f49bd8c96a2 pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0 + 0xf6a2)
                #1  0x00007f49bcbec0d4 _ZN14QWaitCondition4waitEP6QMutex14QDeadlineTimer (libQt5Core.so.5 + 0xd40d4)
                #2  0x00007f49bdfad503 n/a (libQt5Widgets.so.5 + 0x387503)
                #3  0x00007f49bcbe5e8f n/a (libQt5Core.so.5 + 0xcde8f)
                #4  0x00007f49bd8c33e9 start_thread (libpthread.so.0 + 0x93e9)
                #5  0x00007f49bc710293 __clone (libc.so.6 + 0x100293)
```

</details>

**Comment by ebbit1q** [comment]
I can't reproduce this, would you be able to expand on your reproduction steps?

**Comment by skwerlman** [comment]
I can't, unfortunately. I havent been able to cause it again. I can add that i was not the game host, it was a 4-player game, and no other players had conceded.

**Comment by ebbit1q** [comment]
closing due to inactivity
